services:
  - type: web
    name: sipakbkd
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://sipakbkdselayar.my.id
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-sweet-frost-azl56m69-pooler.c-3.ap-southeast-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: DB_NEON_ENDPOINT_ID
        value: ep-sweet-frost-azl56m69
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync
